CREATE DATABASE "tennisDB" OWNER postgres;

-- Création de la table players
CREATE TABLE players
(
    player_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    birth_day DATE NOT NULL,
    rank_id INTEGER NOT NULL,
    points INTEGER NOT NULL,
    CONSTRAINT pk_players PRIMARY KEY (player_id)
);

-- Insertion de quelques données de test
INSERT INTO players (first_name, last_name, birth_day, rank_id, points)
VALUES
    ('Roger', 'Federer', '1981-08-08', 1, 12400),
    ('Rafael', 'Nadal', '1986-06-03', 2, 10150),
    ('Novak', 'Djokovic', '1987-05-22', 3, 11200);
