### GET request to example server
POST http://localhost:8080/api/tennis/players
Content-Type: application/json

{
  "firstName": " jourTestjj",
  "lastName": "last name testkk",
  "birthDay": "2020-10-29",
  "rank": {
    "points": 88,
    "position": 288
  }
}

###