### GET request to example server
POST http://localhost:8080/api/tennis/players
Content-Type: application/json

{
  "firstName": " test",
  "lastName": "tes",
  "birthDay": "2025-10-29",
  "rank": {
    "points": 12,
    "position": 123
  }
}

###